framework:
    cache:
        pools:
            redis_provider:
                # redis
                adapter: cache.adapter.redis
                provider: app.redis_provider
                default_lifetime: 3600

services:
    app.redis_provider:
        class: \Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - '%env(REDIS_DSN)%'
            - { retry_interval: 2, timeout: 10 }
