name: CI Review

on: [pull_request]

permissions:
  contents: write

jobs:
  review:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker-compose -f docker/docker-compose.yml build -t php_container
    - name: Install dependencies
      run: docker run -i -v $PWD:/srv -w/srv php_container composer install
    - name: Run static analysis
      run: docker run -i -v $PWD:/srv -w/srv php_container vendor/bin/phpstan clear-result-cache
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: CI Review Fixes
