
name: Run Tests and Analysis on PR

on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run project
      run: make project

    - name: Run tests
      run: make tests

    - name: Run static analysis
      run: make analysis
