
name: Run Tests and Analysis on PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Build Docker image
      run: docker build -t your_image_name .

    - name: Run make project
      run: make project

    - name: Run tests
      run: make tests

    - name: Run static analysis
      run: make analysis
